### ISSUE TITLE
SealingKey::deriveFromSeedWithSeedString not implemented

### ISSUE THREAD

**Issue by angelix** [dicekeys/seeded-crypto-ios#16]
Method `deriveFromSeedWithSeedString` of `SealingKey` is not implemented.

**Comment by UppaJung** [comment]
@angelix, Is this iOS specific or a problem with the c++ library?

**Comment by angelix** [comment]
It's iOS specific, in Android works.

https://github.com/dicekeys/seeded-crypto-ios/blob/be11af60e505dd6c98725d93393cffb4e336a16b/SeededCrypto/Classes/DSCSealingKey.mm#L18-L23
